version: '3.7'

services:
  academy-preview:
    build:
      context: .
      dockerfile: Dockerfile.prod
    image: localhost:5000/academy-preview:preview
    restart: unless-stopped
    container_name: academy-preview
    networks:
      - traefik-public
    entrypoint: ['/bin/sh', '-c']
    deploy:
      labels:
        - traefik.enable=true
        - traefik.docker.network=traefik-public
        - traefik.constraint-label=traefik-public
        - traefik.http.routers.academy-http.rule=Host(`preview.akademie.lenne.tech`)
        - traefik.http.routers.academy-http.entrypoints=http
        - traefik.http.routers.academy-http.middlewares=https-redirect
        - traefik.http.routers.academy-https.rule=Host(`preview.akademie.lenne.tech`)
        - traefik.http.routers.academy-https.entrypoints=https
        - traefik.http.routers.academy-https.tls=true
        - traefik.http.routers.academy-https.tls.certresolver=le
        - traefik.http.services.academy.loadbalancer.server.port=4000
    command:
      - |
        npx node main.js

volumes:
  node_modules:

networks:
  traefik-public:
    external: true
