version: "3.7"

services:
#  cache:
#    image: redis:latest
#    volumes:
#      - ./redis/config/redis.conf:/usr/local/etc/redis/redis.conf:ro
#    entrypoint: redis-server /usr/local/etc/redis/redis.conf
#
#  mysql:
#    image: mysql
#    volumes:
#      - ./mysql/data/:/var/lib/mysql
#    environment:
#      MYSQL_ROOT_PASSWORD: pimcore
#      MYSQL_DATABASE: pimcore
#      MYSQL_USER: pimcore
#      MYSQL_PASSWORD: pimcore
#    command: ['mysqld', '--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci']
#
#  pimcore:
#    image: pimcore/pimcore:PHP8.0-apache
#    volumes:
#      - ./pimcore/config/php/php.ini:/usr/local/etc/php/php.ini
#      - ./pimcore/logs/apache/:/var/log/apache2
#      - ./pimcore/www/:/var/www/html
#    ports:
#      - "7080:80"

  academy-preview:
    build:
      context: .
      dockerfile: Dockerfile.prod
    image: academy-preview
    restart: unless-stopped
    container_name: academy-preview
#    networks:
#      - traefik-public
    entrypoint: ["/bin/sh","-c"]
    ports:
      - "4000:4000"
    deploy:
      labels:
        - traefik.enable=true
        - traefik.docker.network=traefik-public
        - traefik.constraint-label=traefik-public
        - traefik.http.routers.academy-http.rule=Host(`preview.academy.lenne.tech`)
        - traefik.http.routers.academy-http.entrypoints=http
        - traefik.http.routers.academy-http.middlewares=https-redirect
        - traefik.http.routers.academy-https.rule=Host(`preview.academy.lenne.tech`)
        - traefik.http.routers.academy-https.entrypoints=https
        - traefik.http.routers.academy-https.tls=true
        - traefik.http.routers.academy-https.tls.certresolver=le
        - traefik.http.services.academy.loadbalancer.server.port=8080
    command:
      - |
        npx node main.js

volumes:
  node_modules:

#networks:
#  traefik-public:
#    external: true
