version: '3.7'

services:
  mailcatcher:
    image: schickling/mailcatcher
    ports:
      - '1080:1080'

  website:
    build:
      context: .
      dockerfile: Dockerfile
    image: website-dev
    restart: unless-stopped
    container_name: website-dev
    volumes:
      - .:/var/www/app
      - node_modules:/var/www/app/node_modules
    entrypoint: ['/bin/sh', '-c']
    ports:
      - '4200:4200'
    command:
      - |
        npm install
        npm run dev:ssr
        nginx -g "daemon off;"

volumes:
  node_modules:
