name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to Docker swarm
        uses: wshihadeh/docker-deployment-action@v1
        with:
          remote_docker_host: ssh://deploy@admin.lenne.tech
          ssh_private_key: ${{ secrets.DOCKER_SSH_PRIVATE_KEY }}
          ssh_public_key: ${{ secrets.DOCKER_SSH_PUBLIC_KEY }}
          deployment_mode: docker-swarm
          copy_stack_file: true
          deploy_path: /var/opt/github
          stack_file_name: docker-compose.prod.yml
          keep_files: 5
          args: academy-preview
