name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Deploy to Docker swarm
        run: docker stack deploy -c docker-compose.prod.yml --with-registry-auth academy-preview
