name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js 12.8
        uses: actions/setup-node@v1
        with:
          node-version: 12.8
      - name: Install
        run: npm install
      - name: Build app
        run: npm run build:ssr
      - name: Build
        run: docker-compose -f docker-compose.prod.yml build
      - name: Deploy to Docker swarm
        run: docker stack deploy -c docker-compose.prod.yml --with-registry-auth academy-preview
