name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js 14.17
        uses: actions/setup-node@v1
        with:
          node-version: 14.17.1
      - name: Install
        run: npm install
      - name: Build app
        run: npm run build:ssr
      - name: Build docker
        run: docker-compose -f docker-compose.prod.yml build --pull
      - name: Deploy
        run: docker stack deploy --with-registry-auth --resolve-image=always -c docker-compose.prod.yml academy-preview
